/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Control_FRM_MenuPrincipal;

/**
 *
 * @author PaulaJCh
 */
public class FRM_MenuPrincipal extends javax.swing.JFrame {
    FRM_MantenimientoEstudiante mantenimientoEstudiante;
    FRM_MantenimientoCursos mantenimientoCursos;
    Control_FRM_MenuPrincipal controlador_FRM_MenuPrincipal;
    /**
     * Creates new form FRM_MenuPrincipal
     */
    public FRM_MenuPrincipal() {
        initComponents();
        this.setLocation(100,100);

        controlador_FRM_MenuPrincipal= new Control_FRM_MenuPrincipal();
        mantenimientoEstudiante = new FRM_MantenimientoEstudiante();
        mantenimientoCursos = new FRM_MantenimientoCursos();
        agregarEventos();
    }
     public void agregarEventos(){
        this.jm_Salir.addActionListener(controlador_FRM_MenuPrincipal);
        this.jm_RegistroEstudiantes.addActionListener(controlador_FRM_MenuPrincipal);
        this.jm_RegistroCursos.addActionListener(controlador_FRM_MenuPrincipal);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_Archivo = new javax.swing.JMenu();
        jm_Salir = new javax.swing.JMenuItem();
        jm_Mantenimiento = new javax.swing.JMenu();
        jm_RegistroEstudiantes = new javax.swing.JMenuItem();
        jm_RegistroCursos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ucr1.png"))); // NOI18N

        jm_Archivo.setText("Archivo");

        jm_Salir.setText("Salir");
        jm_Archivo.add(jm_Salir);

        jMenuBar1.add(jm_Archivo);

        jm_Mantenimiento.setText("Mantenimiento");

        jm_RegistroEstudiantes.setText("Registro Estudiantes");
        jm_Mantenimiento.add(jm_RegistroEstudiantes);

        jm_RegistroCursos.setText("Registro Cursos");
        jm_Mantenimiento.add(jm_RegistroCursos);

        jMenuBar1.add(jm_Mantenimiento);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void jm_RegistroEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {                                               
        this.mantenimientoEstudiante.setVisible(true);
    }                                              

    private void jm_RegistroCursosActionPerformed(java.awt.event.ActionEvent evt) {                                          
        this.mantenimientoEstudiante.setVisible(true);
    }                                
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jm_Archivo;
    private javax.swing.JMenu jm_Mantenimiento;
    private javax.swing.JMenuItem jm_RegistroCursos;
    private javax.swing.JMenuItem jm_RegistroEstudiantes;
    private javax.swing.JMenuItem jm_Salir;
    // End of variables declaration//GEN-END:variables
}
