/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Control_FRM_MantenimientoEstudiante;

/**
 *
 * @author PaulaJCh
 */
public class FRM_MantenimientoEstudiante extends javax.swing.JFrame {
    
Control_FRM_MantenimientoEstudiante control_FRM_MantenimientoEstudiante;
    /**
     * Creates new form FRM_MantenimientoEstudiante
     */
    public FRM_MantenimientoEstudiante() {
        initComponents();
        this.setLocation(170,160);
        setVisible(false);
        control_FRM_MantenimientoEstudiante = new Control_FRM_MantenimientoEstudiante(this);
         gUI_Botones1.agregarEventos(control_FRM_MantenimientoEstudiante);
         
    }
    public String[] devolverInformacion()
    {
        return this.gUI_RegistroEstudiantes1.devolverInformacion();
    }
    
    public String devolverCarnet()
    {
        return this.gUI_RegistroEstudiantes1.devolverCarnet();
    }
    
    public void mostrarInformacion(String arreglo[])
    {
        this.gUI_RegistroEstudiantes1.mostrarInformacion(arreglo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gUI_Botones1 = new Vista.GUI_Botones();
        gUI_RegistroEstudiantes1 = new Vista.GUI_RegistroEstudiantes();
        jLabel1 = new javax.swing.JLabel();

        gUI_RegistroEstudiantes1.setForeground(new java.awt.Color(0, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Registro Estudiantes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(gUI_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(gUI_RegistroEstudiantes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(gUI_RegistroEstudiantes1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gUI_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_Botones gUI_Botones1;
    private Vista.GUI_RegistroEstudiantes gUI_RegistroEstudiantes1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

        
}
