/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author PaulaJCh
 */
public class GUI_RegistroCursos extends javax.swing.JPanel {

    /**
     * Creates new form GUI_RegistroCursos
     */
    public GUI_RegistroCursos() {
        initComponents();
        
    }
     public String[] devolverInformacion()
    {
        String arreglo[];
        arreglo=new String[3];
        arreglo[0]=this.jt_Nombre.getText();
        arreglo[1]=this.jt_Siglas.getText();
        arreglo[2]=this.jt_Creditos.getText();
        
        return arreglo;
    }
      public String devolverSiglas()
    {
        return jt_Siglas.getText();
    }
      public void mostrarInformacion(String arreglo[])
    {
        this.jt_Nombre.setText(arreglo[0]);
        this.jt_Siglas.setText(arreglo[1]);
        this.jt_Creditos.setText(arreglo[2]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_NombreC = new javax.swing.JLabel();
        jl_Siglas = new javax.swing.JLabel();
        jl_Creditos = new javax.swing.JLabel();
        jt_Nombre = new javax.swing.JTextField();
        jt_Siglas = new javax.swing.JTextField();
        jt_Creditos = new javax.swing.JTextField();

        jl_NombreC.setText("Nombre");

        jl_Siglas.setText("Siglas");

        jl_Creditos.setText("Créditos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_NombreC)
                    .addComponent(jl_Siglas)
                    .addComponent(jl_Creditos))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jt_Creditos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                        .addComponent(jt_Siglas, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_NombreC)
                    .addComponent(jt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Siglas)
                    .addComponent(jt_Siglas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Creditos)
                    .addComponent(jt_Creditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jl_Creditos;
    private javax.swing.JLabel jl_NombreC;
    private javax.swing.JLabel jl_Siglas;
    private javax.swing.JTextField jt_Creditos;
    private javax.swing.JTextField jt_Nombre;
    private javax.swing.JTextField jt_Siglas;
    // End of variables declaration//GEN-END:variables
}
